### ISSUE TITLE
Start.py

### ISSUE THREAD

**Issue by rodrigopereiraa** [Times-0/Timeline#10]
When executing Start.py gives this error

> Traceback (most recent call last):
  File "Start.py", line 94, in HotLoadModule
    return Handler.startLoadingModules()
  File "/CPPS/Timeline/Timeline/Utils/Modules.py", line 220, in startLoadingModules
    Defer.addErrback(self.loadingException)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 333, in addErrback
    errbackKeywords=kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/CPPS/Timeline/Timeline/Utils/Modules.py", line 212, in loadingException
    sys.exit(0)
exceptions.SystemExit: 0

> 

  CRITICAL | 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/CPPS/Timeline/Timeline/Utils/Modules.py", line 212, in loadingException
    sys.exit(0)
SystemExit: 

> 0

Also would be great if you could contact me on discord , please leave your discord.

**Comment by valid22** [comment]
valid22#1856
