### ISSUE TITLE
Setup troubles with MySQLdb

### ISSUE THREAD

**Issue by zacpaton** [Times-0/Timeline#37]
```
 ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dImAwq/mysql-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dImAwq/mysql-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cuYMOj
         cwd: /tmp/pip-install-dImAwq/mysql-python/
    Complete output (10 lines):
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dImAwq/mysql-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
On Ubuntu 20.04.1
When attempting to install MySQLdb by doing 'sudo pip install MySQL-Python' I get the above error - I looked around and it seems like it's no longer supported/usable? I have tried updating setup tools but it changes nothing.

On the readme under requirements it says that you can use an alternative connector? It also lists mysql-connector-python, so I went and installed that - then it said to change line 31 of __init__.py in the Database folder in timeline. It could be me missing something - but I dont see any easy to change variable in there to direct it to mysql-connector-python instead of MySQLdb

Thanks to anyone who can help

**Comment by valid22** [comment]
https://github.com/Times-0/Timeline#installing-mysql-python-mysqldb

read the part where it tells you how to install mysqldb
